version: 0.2

phases:
  pre_build:
    commands:
      # Install dependencies needed for running tests
      - echo Installing application dependencies
      - npm install

        # Upgrade AWS CLI to the latest version
      - pip install --upgrade awscli

  build:
    commands:
      - echo Building project
