<template>
  <v-card class="shake-bottom" width="100%" @click="cardClick()">
    <v-img
      v-if="card.imageUrl"
      max-height="300px"
      :src="`https://res.cloudinary.com/euyome/image/upload/${card.imageUrl}`"
    ></v-img>
    <v-card-title class="pb-1 pt-4 flex-column align-start">
      <div v-if="card.subtitle" class="text-caption">{{ card.subtitle }}</div>
      <div>{{ card.title }}</div>
    </v-card-title>
    <v-card-text class="text-justify">{{ card.content }}</v-card-text>
  </v-card>
</template>

<script lang="ts">
import Vue from 'vue';
import { Profile, Style, Card } from '~/types';

export default Vue.extend({
  props: {
    profile: { type: Object as () => Profile, required: true },
  },

  computed: {
    theme(): Style {
      if (this.profile.style) {
        return this.profile.style;
      }
      return this.$store.getters.defaultProfile;
    },

    card(): Card {
      return this.profile.card!;
    },
  },

  methods: {
    async cardClick(): Promise<void> {
      await this.$axios.post(`/views/click/card/${this.profile.id}`);
      window.location.href = this.card.buttonLink;
    },
  },
});
</script>

<style lang="scss" scoped>
/* ----------------------------------------------
 * Generated by Animista on 2021-1-25 16:18:6
 * Licensed under FreeBSD License.
 * See http://animista.net/license for more info.
 * w: http://animista.net, t: @cssanimista
 * ---------------------------------------------- */

.shake-bottom {
  -webkit-animation: shake-bottom 1.5s 2s
    cubic-bezier(0.455, 0.03, 0.515, 0.955) both;
  animation: shake-bottom 0.8s 4s cubic-bezier(0.455, 0.03, 0.515, 0.955) both;
}

/**
 * ----------------------------------------
 * animation shake-bottom
 * ----------------------------------------
 */
@-webkit-keyframes shake-bottom {
  0%,
  100% {
    -webkit-transform: rotate(0deg);
    transform: rotate(0deg);
    -webkit-transform-origin: 50% 100%;
    transform-origin: 50% 100%;
  }
  10% {
    -webkit-transform: rotate(1deg);
    transform: rotate(1deg);
  }
  20%,
  40%,
  60% {
    -webkit-transform: rotate(-2deg);
    transform: rotate(-2deg);
  }
  30%,
  50%,
  70% {
    -webkit-transform: rotate(2deg);
    transform: rotate(2deg);
  }
  80% {
    -webkit-transform: rotate(-1deg);
    transform: rotate(-1deg);
  }
  90% {
    -webkit-transform: rotate(1deg);
    transform: rotate(1deg);
  }
}

@keyframes shake-bottom {
  0%,
  100% {
    -webkit-transform: rotate(0deg);
    transform: rotate(0deg);
    -webkit-transform-origin: 50% 100%;
    transform-origin: 50% 100%;
  }
  10% {
    -webkit-transform: rotate(1deg);
    transform: rotate(1deg);
  }
  20%,
  40%,
  60% {
    -webkit-transform: rotate(-2deg);
    transform: rotate(-2deg);
  }
  30%,
  50%,
  70% {
    -webkit-transform: rotate(2deg);
    transform: rotate(2deg);
  }
  80% {
    -webkit-transform: rotate(-1deg);
    transform: rotate(-1deg);
  }
  90% {
    -webkit-transform: rotate(1deg);
    transform: rotate(1deg);
  }
}
</style>
