<template>
  <div>
    <section class="hero">
      <div class="hero_smartphone">
        <img :src="require('~/assets/images/cover.png')" />
      </div>

      <div class="hero_title">Você a um clique</div>

      <div class="hero_action">
        <p class="hero_action_title">
          Cadastre-se <span class="highlight"> grátis </span>
        </p>
        <button @click="$router.push('/register')">agora mesmo</button>
        <p class="hero_action_counter">Já somos 9K euyome's</p>
      </div>
    </section>

    <About />
    <Showcases />
  </div>
</template>

<script lang="ts">
import Vue from 'vue';
import About from '@/components/About.vue';
import Showcases from '@/components/Showcases.vue';

export default Vue.extend({
  components: {
    About,
    Showcases,
  },
});
</script>

<style lang="scss" scoped>
@import url('https://fonts.googleapis.com/css2?family=Rubik:wght@300;400;500;700;900&display=swap');

.highlight {
  background: #fff;
  color: #7ebc89;
  padding: 0.3rem 1rem;
  border-radius: 6px;
  font-weight: 900;
}

.hero {
  position: relative;
  display: grid;
  grid-template-areas:
    'image'
    'title'
    'action';

  width: 100%;

  .hero_title {
    grid-area: title;
    place-self: center;

    margin: 2rem 0;
    line-height: min(4.4rem, 15vw);
    font-size: min(4.4rem, 15vw);
    font-weight: 900;
    text-align: center;
    text-transform: uppercase;
  }

  .hero_action {
    grid-area: action;
    display: flex;
    flex-direction: column;
    width: 100%;
    height: 100%;
    padding: 2rem 0;
    margin: 1rem 0;

    align-items: center;
    justify-content: center;
    background: #7ebc89;

    .hero_action_title {
      font-size: 2rem;
      font-weight: 900;
      color: #fff;
      text-transform: uppercase;
      text-align: center;
    }

    button {
      width: 80%;
      max-width: 80%;
      padding: 0.8rem 2rem;
      margin-top: 1rem;
      border-radius: 12px;
      outline: none;
      font-size: min(2rem, 7vw);

      font-weight: 900;
      text-transform: uppercase;
      background: #fe5d26;
      color: #fff;

      transition: all 250ms ease 0s;

      -webkit-animation: pulsate-fwd 1.5s ease-in-out infinite both;
      animation: pulsate-fwd 1.5s ease-in-out infinite both;

      &:hover {
        background: red;
        -webkit-animation: none;
        animation: none;
      }
    }

    .hero_action_counter {
      font-size: 0.8rem;
      font-weight: 600;
      margin-top: 0.5rem;
      color: white;
    }
  }

  .hero_smartphone {
    grid-area: image;
    place-self: center;
    margin-top: 1rem;
    img {
      width: 180px;
    }
  }
}

@media only screen and (min-width: 780px) {
  .hero {
    grid-template-columns: 1fr 1fr;
    grid-template-areas:
      'title action action'
      'image action action';
    height: calc(100vh - 100px);

    .hero_title {
      line-height: min(3.4rem, 10vw);
      font-size: min(3.4rem, 10vw);
      width: 80%;
    }
    .hero_action {
      margin: 0;
      .hero_action_title {
        width: 80%;
        font-size: 4.2vw;
      }
    }
  }
}

@media only screen and (min-width: 1024px) {
  .hero {
    grid-template-columns: 2fr 1fr 1fr 2fr;
    grid-template-areas: 'title image action action';

    .hero_title {
      line-height: min(4.4rem, 10vw);
      font-size: min(4.4rem, 10vw);
      text-align: left;
      margin-left: 4vw;
    }

    .hero_action {
      padding: 2rem 0;
      margin: 0;

      align-items: center;
      justify-content: center;

      .hero_action_title {
        width: 80%;
        font-size: 4.2vw;
      }

      button {
        width: 70%;
        max-width: 70%;
      }
    }
  }
  .hero_smartphone {
    margin-right: -6rem;
    z-index: 1;
    img {
      min-width: 220px;
    }
  }
}

/* ----------------------------------------------
 * Generated by Animista on 2020-9-14 15:38:14
 * Licensed under FreeBSD License.
 * See http://animista.net/license for more info.
 * w: http://animista.net, t: @cssanimista
 * ---------------------------------------------- */

/**
 * ----------------------------------------
 * animation pulsate-fwd
 * ----------------------------------------
 */
@-webkit-keyframes pulsate-fwd {
  0% {
    -webkit-transform: scale(1);
    transform: scale(1);
  }
  50% {
    -webkit-transform: scale(1.03);
    transform: scale(1.03);
  }
  100% {
    -webkit-transform: scale(1);
    transform: scale(1);
  }
}
@keyframes pulsate-fwd {
  0% {
    -webkit-transform: scale(1);
    transform: scale(1);
  }
  15% {
    -webkit-transform: scale(1.03);
    transform: scale(1.03);
  }
  100% {
    -webkit-transform: scale(1);
    transform: scale(1);
  }
}
</style>
